---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-inspect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-inspect
  template:
    metadata:
      labels:
        app: node-inspect
    spec:
      containers:
      - name: main
        image: gcr.io/foo/bar
        ports:
          - containerPort: 8080
          - containerPort: 9229
